version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-linkedin
    environment:
      MYSQL_DATABASE: linkedin
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend

  redis:
    image: redis:latest
    container_name: redis-linkedin
    ports:
      - '6379:6379'
#    restart: always
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    networks:
      - backend

volumes:
  mysql-data:
  redis-data:

networks:
  backend:
