spring:
  application:
    name: backend
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/linkedin?createDatabaseIfNotExist=true}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: true
    properties:
      hibernate:
        format_sql: true
        search:
          backend:
            type: lucene
            directory:
              root: ./lucene/indexes
            automatic_indexing:
              synchronization:
                strategy: queued
#   If you want deployment with Redis, uncomment the following lines:
#  data:
#    redis:
#      host: ${REDIS_HOST:localhost}
#      port: ${REDIS_PORT:6379}
#      username: ${REDIS_USERNAME:default}
#      password: ${REDIS_PASSWORD:default}
#      ssl:
#        enabled: true
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

jwt:
  signerKey: ${JWT_SIGNER_KEY}

brevo:
  apiKey: ${BREVO_API_KEY}
  email: "nrin31266@gmail.com"
  name: "Linkedin clone by VanRin05"

oauth:
  client:
    id: ${OAUTH_CLIENT_ID}
    secret: ${OAUTH_CLIENT_SECRET}

server:
  address: 0.0.0.0
  servlet:
    context-path: /api/v1
  port: 8080

