spring:
  application:
    name: backend
  datasource:
    url: 'jdbc:mysql://localhost:3306/linkedin?createDatabaseIfNotExist=true'
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379

jwt:
  signerKey: "HDKdDVDEpABtpunTzN2QM2pbmVzDP5jht6WGykegNKgsKDVdDlbzFVmU1vDOVOHV"

brevo:
  apiKey: ${BREVO_API_KEY}
  email: "nrin31266@gmail.com"
  name: "Linkedin clone by VanRin05"

oauth:
  client:
    id: ${OAUTH_CLIENT_ID}
    secret: ${OAUTH_CLIENT_SECRET}

server:
  address: 0.0.0.0
  servlet:
    context-path: /api/v1
  port: 8080

